from __future__ import annotations

from typing import Any

from pymilvus import (
    AnnSearchRequest,
    DataType,
    Function,
    FunctionType,
    MilvusClient,
    RRFRanker,
)

from .repository import MovieRecord
from .schemas import SearchRequest


class MovieVectorStore:
    OUTPUT_FIELDS = [
        "movie_id",
        "title",
        "original_title",
        "tagline",
        "overview",
        "genres",
        "keywords",
        "release_year",
        "vote_average",
        "popularity",
    ]

    DENSE_FIELDS = (
        "dense_grouped",
        "dense_overview",
        "dense_title_tagline",
    )

    def __init__(
        self,
        uri: str,
        collection: str,
        dimension: int,
        rrf_k: int,
        candidate_multiplier: int,
        semantic_accept_normalized_score: float,
        semantic_strong_normalized_score: float,
    ):
        self.client = MilvusClient(uri=uri)
        self.collection = collection
        self.dimension = dimension
        self.rrf_k = rrf_k
        self.candidate_multiplier = candidate_multiplier
        self.semantic_accept_normalized_score = semantic_accept_normalized_score
        self.semantic_strong_normalized_score = semantic_strong_normalized_score

    def ping(self) -> bool:
        try:
            self.client.list_collections()
            return True
        except Exception:
            return False

    def exists(self) -> bool:
        return self.client.has_collection(self.collection)

    def ensure_collection(self) -> None:
        if self.exists():
            self.client.load_collection(self.collection)
            return

        schema = self.client.create_schema(auto_id=False, enable_dynamic_field=False)
        schema.add_field("movie_id", DataType.INT64, is_primary=True)
        schema.add_field("title", DataType.VARCHAR, max_length=1024)
        schema.add_field("original_title", DataType.VARCHAR, max_length=1024)
        schema.add_field("tagline", DataType.VARCHAR, max_length=4096)
        schema.add_field("overview", DataType.VARCHAR, max_length=32768)
        schema.add_field("genres", DataType.VARCHAR, max_length=4096)
        schema.add_field("keywords", DataType.VARCHAR, max_length=32768)
        schema.add_field("release_year", DataType.INT64, nullable=True)
        schema.add_field("vote_average", DataType.FLOAT, nullable=True)
        schema.add_field("popularity", DataType.FLOAT, nullable=True)
        schema.add_field(
            "document",
            DataType.VARCHAR,
            max_length=65535,
            enable_analyzer=True,
            analyzer_params={"tokenizer": "standard", "filter": ["lowercase"]},
        )

        # Three independent dense representations for the same movie entity.
        schema.add_field("dense_grouped", DataType.FLOAT_VECTOR, dim=self.dimension)
        schema.add_field("dense_overview", DataType.FLOAT_VECTOR, dim=self.dimension)
        schema.add_field("dense_title_tagline", DataType.FLOAT_VECTOR, dim=self.dimension)

        # BM25 stays on the grouped/raw document and is generated by Milvus.
        schema.add_field("sparse", DataType.SPARSE_FLOAT_VECTOR)
        schema.add_function(
            Function(
                name="document_bm25",
                input_field_names=["document"],
                output_field_names=["sparse"],
                function_type=FunctionType.BM25,
            )
        )

        indexes = self.client.prepare_index_params()
        for field_name in self.DENSE_FIELDS:
            indexes.add_index(
                field_name=field_name,
                index_type="AUTOINDEX",
                metric_type="COSINE",
            )
        indexes.add_index(
            field_name="sparse",
            index_type="SPARSE_INVERTED_INDEX",
            metric_type="BM25",
            params={
                "inverted_index_algo": "DAAT_MAXSCORE",
                "bm25_k1": 1.2,
                "bm25_b": 0.75,
            },
        )

        self.client.create_collection(
            collection_name=self.collection,
            schema=schema,
            index_params=indexes,
            consistency_level="Bounded",
        )
        self.client.load_collection(self.collection)

    def reset_collection(self) -> None:
        if self.exists():
            self.client.drop_collection(self.collection)
        self.ensure_collection()

    def row_count(self) -> int | None:
        if not self.exists():
            return 0
        try:
            stats = self.client.get_collection_stats(self.collection)
            value = stats.get("row_count") or stats.get("rowCount")
            return int(value) if value is not None else None
        except Exception:
            try:
                result = self.client.query(
                    collection_name=self.collection,
                    filter="",
                    output_fields=["count(*)"],
                )
                if result:
                    return int(result[0].get("count(*)", 0))
            except Exception:
                pass
        return None

    def replace(
        self,
        records: list[MovieRecord],
        grouped_vectors: list[list[float]],
        overview_vectors: list[list[float]],
        title_tagline_vectors: list[list[float]],
    ) -> int:
        expected = len(records)
        if not (
            len(grouped_vectors) == expected
            and len(overview_vectors) == expected
            and len(title_tagline_vectors) == expected
        ):
            raise ValueError("records/vector batch length mismatch")

        entities: list[dict[str, Any]] = []
        for record, grouped_vector, overview_vector, title_tagline_vector in zip(
            records,
            grouped_vectors,
            overview_vectors,
            title_tagline_vectors,
            strict=True,
        ):
            entities.append(
                {
                    "movie_id": record.movie_id,
                    "title": record.title[:1024],
                    "original_title": record.original_title[:1024],
                    "tagline": record.tagline[:4096],
                    "overview": record.overview[:32768],
                    "genres": "|".join(record.genres)[:4096],
                    "keywords": "|".join(record.keywords)[:32768],
                    "release_year": record.release_year,
                    "vote_average": record.vote_average,
                    "popularity": record.popularity,
                    "document": record.grouped_document()[:65535],
                    "dense_grouped": grouped_vector,
                    "dense_overview": overview_vector,
                    "dense_title_tagline": title_tagline_vector,
                }
            )

        if entities:
            self.client.upsert(collection_name=self.collection, data=entities)
        return len(entities)

    @staticmethod
    def _filter(request: SearchRequest) -> str:
        parts: list[str] = []
        if request.year_from is not None:
            parts.append(f"release_year >= {int(request.year_from)}")
        if request.year_to is not None:
            parts.append(f"release_year <= {int(request.year_to)}")
        if request.min_vote_average is not None:
            parts.append(f"vote_average >= {float(request.min_vote_average)}")
        if request.genre:
            # `genres` uses a | separated scalar field. LIKE keeps this filter
            # simple while vector/BM25 retrieval remains the primary matcher.
            safe_genre = request.genre.replace("\\", "\\\\").replace('"', '\\"')
            parts.append(f'genres like "%{safe_genre}%"')
        return " and ".join(parts)

    @staticmethod
    def _hit_to_dict(hit: Any) -> dict[str, Any]:
        entity = getattr(hit, "entity", None)
        if entity is None and isinstance(hit, dict):
            entity = hit.get("entity", {})
        entity = entity or {}

        def get_value(name: str, default: Any = None) -> Any:
            if hasattr(entity, "get"):
                value = entity.get(name)
                return default if value is None else value
            return default

        score = getattr(hit, "score", None)
        if score is None:
            score = getattr(hit, "distance", None)
        if score is None and isinstance(hit, dict):
            score = hit.get("score", hit.get("distance", 0.0))

        genres = [x for x in str(get_value("genres", "")).split("|") if x]
        keywords = [x for x in str(get_value("keywords", "")).split("|") if x]
        movie_id = get_value("movie_id", getattr(hit, "id", 0))

        return {
            "movie_id": int(movie_id),
            "score": float(score or 0.0),
            "title": str(get_value("title", "")),
            "original_title": str(get_value("original_title", "")),
            "tagline": str(get_value("tagline", "")),
            "overview": str(get_value("overview", "")),
            "genres": genres,
            "keywords": keywords,
            "release_year": get_value("release_year"),
            "vote_average": get_value("vote_average"),
            "popularity": get_value("popularity"),
        }

    def _dense_requests(
        self,
        query_vector: list[float],
        *,
        limit: int,
        expr: str | None,
    ) -> list[AnnSearchRequest]:
        return [
            AnnSearchRequest(
                data=[query_vector],
                anns_field=field_name,
                param={"metric_type": "COSINE", "params": {}},
                limit=limit,
                expr=expr,
            )
            for field_name in self.DENSE_FIELDS
        ]

    def search(self, request: SearchRequest, query_vector: list[float] | None) -> list[dict[str, Any]]:
        self.client.load_collection(self.collection)
        expr = self._filter(request)
        filter_expr = expr or None
        candidates = min(max(request.limit * self.candidate_multiplier, request.limit), 1000)

        if request.mode == "bm25":
            result = self.client.search(
                collection_name=self.collection,
                data=[request.query],
                anns_field="sparse",
                search_params={"metric_type": "BM25", "params": {}},
                filter=filter_expr,
                limit=request.limit,
                output_fields=self.OUTPUT_FIELDS,
            )
        else:
            if query_vector is None:
                raise ValueError(f"{request.mode} search requires a query vector")

            # The exact same query embedding is compared independently with the
            # grouped, overview-only, and title+tagline vectors.
            requests = self._dense_requests(
                query_vector,
                limit=candidates,
                expr=filter_expr,
            )

            if request.mode == "hybrid":
                requests.append(
                    AnnSearchRequest(
                        data=[request.query],
                        anns_field="sparse",
                        param={"metric_type": "BM25", "params": {}},
                        limit=candidates,
                        expr=filter_expr,
                    )
                )

            result = self.client.hybrid_search(
                collection_name=self.collection,
                reqs=requests,
                ranker=RRFRanker(self.rrf_k),
                limit=request.limit,
                output_fields=self.OUTPUT_FIELDS,
            )

        hits = result[0] if result else []
        converted = [self._hit_to_dict(hit) for hit in hits]

        # RRF scores are small raw reciprocal-rank sums. Normalize them against
        # the theoretical rank-1 maximum so quality thresholds are stable when
        # RRF_K changes and understandable on a 0..1 scale. BM25 scores are not
        # normalized because their scale is corpus/query dependent.
        if request.mode in {"hybrid", "dense"}:
            source_count = len(self.DENSE_FIELDS) + (1 if request.mode == "hybrid" else 0)
            max_rrf_score = source_count / float(self.rrf_k + 1)
            for hit in converted:
                normalized = min(max(hit["score"] / max_rrf_score, 0.0), 1.0) if max_rrf_score else 0.0
                hit["normalized_score"] = normalized
                if normalized >= self.semantic_strong_normalized_score:
                    hit["quality"] = "strong"
                elif normalized >= self.semantic_accept_normalized_score:
                    hit["quality"] = "acceptable"
                else:
                    hit["quality"] = "weak"
        else:
            for hit in converted:
                hit["normalized_score"] = None
                hit["quality"] = "unscored"
        return converted
