import pandas as pd
import numpy as np
import json

movies_data = pd.read_csv('tmdb_5000_movies.csv')
credits_data = pd.read_csv('tmdb_5000_credits.csv')
credits_data.drop(['title'], axis=1, inplace=True)
data = pd.merge(movies_data, credits_data, left_on='id', right_on='movie_id', how='left', suffixes=('_movies', '_credits'))
data.drop(['movie_id'], axis=1, inplace=True)

print("Data Columns:")
for k in data.keys():
    print(k)

assert len(data) == len(movies_data) == len(credits_data), "Data length mismatch after merge"


## After reviewing the data, we will have the following tables:
# 1- Movies Table: This table will contain the following columns:
# - id: The unique identifier for each movie.
# - title: The title of the movie.
# - original_title: The original title of the movie.
# - tagline: The tagline of the movie.
# - budget: The budget of the movie.
# - homepage: The homepage URL of the movie.
# - original_language: The original language of the movie.
# - popularity: The popularity score of the movie.
# - release_date: The release date of the movie.
# - revenue: The revenue generated by the movie.
# - runtime: The runtime of the movie in minutes.
# - status: The status of the movie (e.g., Released, Post Production).
# - vote_average: The average vote score of the movie.
# - vote_count: The total number of votes received by the movie.

# 2- genres Table.
# 3- Movie_Genres Table: This table will contain the following columns: (Associative table between movies and genres)
# 4- production_companies Table.
# 5- Movie_Production_Companies Table: This table will contain the following columns: (Associative table between movies and production companies)
# 6- production_countries Table.
# 7- Movie_Production_Countries Table: This table will contain the following columns: (Associative table between movies and production countries)
# 8- spoken_languages Table.
# 9- Movie_Spoken_Languages Table: This table will contain the following columns: (Associative table between movies and spoken languages)
# 10- cast Table.
# 11- Movie_Cast Table: This table will contain the following columns: (Associative table between movies and cast)
# 12- crew Table.
# 13- Movie_Crew Table: This table will contain the following columns: (Associative table between movies and crew)

movies_columns = ['id', 'title', 'budget', 'homepage', 'original_language', 'original_title', 'popularity', 'release_date', 'revenue', 'runtime', 'status', 'tagline', 'vote_average', 'vote_count']
movies_table = data[movies_columns]
print("Movies Table: Ok")

## Prepare the genres table and the associative table between movies and genres
genres_data = data[['id', 'genres']]
## get unique genres
unique_genres = set()
for genres in genres_data['genres']:
    if pd.notnull(genres):
        genres_list = json.loads(genres)
        for genre in genres_list:
            unique_genres.add((genre['id'], genre['name']))

genres_table = pd.DataFrame(list(unique_genres), columns=['id', 'name'])
print("Genres Table: Ok")

## Prepare the associative table between movies and genres
movie_genres_table = []
for _, row in genres_data.iterrows():
    movie_id = row['id']
    if pd.notnull(row['genres']):
        genres_list = json.loads(row['genres'])
        for genre in genres_list:
            movie_genres_table.append((movie_id, genre['id']))

movie_genres_table = pd.DataFrame(movie_genres_table, columns=['movie_id', 'genre_id'])
print("Movie Genres Table: Ok")

## Prepare the production_companies table and the associative table between movies and production companies
production_companies_data = data[['id', 'production_companies']]
## get unique production companies
unique_production_companies = set()
for companies in production_companies_data['production_companies']:
    if pd.notnull(companies):
        companies_list = json.loads(companies)
        for company in companies_list:
            unique_production_companies.add((company['id'], company['name']))

production_companies_table = pd.DataFrame(list(unique_production_companies), columns=['id', 'name'])
print("Production Companies Table: Ok")

## Prepare the associative table between movies and production companies
movie_production_companies_table = []
for _, row in production_companies_data.iterrows():
    movie_id = row['id']
    if pd.notnull(row['production_companies']):
        companies_list = json.loads(row['production_companies'])
        for company in companies_list:
            movie_production_companies_table.append((movie_id, company['id']))

movie_production_companies_table = pd.DataFrame(movie_production_companies_table, columns=['movie_id', 'company_id'])
print("Movie Production Companies Table: Ok")

## Prepare the production_countries table and the associative table between movies and production countries
production_countries_data = data[['id', 'production_countries']]
## get unique production countries
unique_production_countries = set()
for countries in production_countries_data['production_countries']:
    if pd.notnull(countries):
        countries_list = json.loads(countries)
        for country in countries_list:
            unique_production_countries.add((country['iso_3166_1'], country['name']))

production_countries_table = pd.DataFrame(list(unique_production_countries), columns=['iso_3166_1', 'name'])
print("Production Countries Table: Ok")

## Prepare the associative table between movies and production countries
movie_production_countries_table = []
for _, row in production_countries_data.iterrows():
    movie_id = row['id']
    if pd.notnull(row['production_countries']):
        countries_list = json.loads(row['production_countries'])
        for country in countries_list:
            movie_production_countries_table.append((movie_id, country['iso_3166_1']))

movie_production_countries_table = pd.DataFrame(movie_production_countries_table, columns=['movie_id', 'country_iso_3166_1'])
print("Movie Production Countries Table: Ok")

## Prepare the spoken_languages table and the associative table between movies and spoken languages
spoken_languages_data = data[['id', 'spoken_languages']]
## get unique spoken languages
unique_spoken_languages = set()
for languages in spoken_languages_data['spoken_languages']:
    if pd.notnull(languages):
        languages_list = json.loads(languages)
        for language in languages_list:
            unique_spoken_languages.add((language['iso_639_1'], language['name']))

spoken_languages_table = pd.DataFrame(list(unique_spoken_languages), columns=['iso_639_1', 'name'])
print("Spoken Languages Table: Ok")

## Prepare the associative table between movies and spoken languages
movie_spoken_languages_table = []
for _, row in spoken_languages_data.iterrows():
    movie_id = row['id']
    if pd.notnull(row['spoken_languages']):
        languages_list = json.loads(row['spoken_languages'])
        for language in languages_list:
            movie_spoken_languages_table.append((movie_id, language['iso_639_1']))
movie_spoken_languages_table = pd.DataFrame(movie_spoken_languages_table, columns=['movie_id', 'language_iso_639_1'])
print("Movie Spoken Languages Table: Ok")

## Prepare the cast table and the associative table between movies and cast
cast_data = data[['id', 'cast']]
## get unique cast members
unique_cast = set()
for casts in cast_data['cast']:
    if pd.notnull(casts):
        casts_list = json.loads(casts)
        for cast in casts_list:
            unique_cast.add((cast['cast_id'], cast['name'], cast['character'], cast['gender'], cast['order']))

cast_table = pd.DataFrame(list(unique_cast), columns=['cast_id', 'name', 'character', 'gender', 'order'])
print("Cast Table: Ok")

## Prepare the associative table between movies and cast
movie_cast_table = []
for _, row in cast_data.iterrows():
    movie_id = row['id']
    if pd.notnull(row['cast']):
        casts_list = json.loads(row['cast'])
        for cast in casts_list:
            movie_cast_table.append((movie_id, cast['cast_id']))

movie_cast_table = pd.DataFrame(movie_cast_table, columns=['movie_id', 'cast_id'])
print("Movie Cast Table: Ok")

## Prepare the crew table and the associative table between movies and crew
crew_data = data[['id', 'crew']]
## get unique crew members
unique_crew = set()
for crews in crew_data['crew']:
    if pd.notnull(crews):
        crews_list = json.loads(crews)
        for crew in crews_list:
            unique_crew.add((crew['credit_id'], crew['name'], crew['department'], crew['job'], crew['gender']))

crew_table = pd.DataFrame(list(unique_crew), columns=['credit_id', 'name', 'department', 'job', 'gender'])
print("Crew Table: Ok")
## Prepare the associative table between movies and crew
movie_crew_table = []
for _, row in crew_data.iterrows():
    movie_id = row['id']
    if pd.notnull(row['crew']):
        crews_list = json.loads(row['crew'])
        for crew in crews_list:
            movie_crew_table.append((movie_id, crew['credit_id']))

movie_crew_table = pd.DataFrame(movie_crew_table, columns=['movie_id', 'credit_id'])
print("Movie Crew Table: Ok")

## Finally, we will save all the tables to CSV files for further use
movies_table.to_csv('movies_table.csv', index=False)
genres_table.to_csv('genres_table.csv', index=False)
movie_genres_table.to_csv('movie_genres_table.csv', index=False)
production_companies_table.to_csv('production_companies_table.csv', index=False)
movie_production_companies_table.to_csv('movie_production_companies_table.csv', index=False)
production_countries_table.to_csv('production_countries_table.csv', index=False)
movie_production_countries_table.to_csv('movie_production_countries_table.csv', index=False)
spoken_languages_table.to_csv('spoken_languages_table.csv', index=False)
movie_spoken_languages_table.to_csv('movie_spoken_languages_table.csv', index=False)
cast_table.to_csv('cast_table.csv', index=False)
movie_cast_table.to_csv('movie_cast_table.csv', index=False)
crew_table.to_csv('crew_table.csv', index=False)
movie_crew_table.to_csv('movie_crew_table.csv', index=False)
print("All tables saved to CSV files.")

## Remaining columnns in the movies table are: Overview, Keywords. We will use them together with the tagline in the Vector DB for semantic retrieval.
## Fuzzy search will be used for title, original_title and homepage.